"""Capability data for the Creator Agent (agent_key="creator").

Purpose (from mission spec): Content/video production brain: scripts, VEO
prompts, captions, thumbnails, calendars, campaign creative.

Live MVP behavior:
- Generate scripts, prompts, captions, calendars.
- Do not publish automatically. Publishing requires approval.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "creator"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Stored in the DB-backed content/memory table, keyed by user_id + workspace_id; never mixed across tenants."
EPHEMERAL = "Held only for the lifetime of the active generation request; not persisted to durable storage."
APPROVAL_GATED = "Persisted/released only after explicit user approval; nothing is marked publish-ready until approved."
NOT_PERSISTED = "Not persisted; the response is generated on demand and returned directly to the caller."

SCHEMA_CHECK = "VerificationAgent confirms response matches the normalized result schema."
DB_CHECK = "VerificationAgent confirms the expected row exists/changed in the content table for the scoped user_id/workspace_id."
AUDIT_CHECK = "VerificationAgent confirms a matching audit log row was written for this action."
PUBLISH_GATE_CHECK = "VerificationAgent confirms no publish action executed without a corresponding approval record."

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "Video ad scripts", "Generate a text video-ad script from a brief.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text video-ad script using the configured LLM; returned as plain text, never rendered or published.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(2, "Short-form hooks", "Generate opening hook lines for short-form video.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a list of candidate hook lines as text; nothing is filmed or published.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(3, "VEO 3 prompts", "Generate a text prompt for VEO 3 video generation.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text VEO 3 prompt; returned to the caller, no video is rendered by this agent.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(4, "VEO JSON prompts", "Generate a structured JSON prompt object for VEO video generation.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a schema-validated VEO JSON prompt object; returned to the caller, no video is rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(5, "Scene-by-scene storyboards", "Generate a text storyboard breaking a script into scenes.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a scene-by-scene text storyboard from an input script; no image/video is rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(6, "Voiceover timing", "Estimate per-line voiceover timing for a script.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes estimated per-line voiceover timing from script text using a words-per-minute heuristic; no audio is rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(7, "Captions/subtitles", "Generate caption/subtitle text for a script or video.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates caption/subtitle text from a script or provided transcript; returned as plain text.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(8, "Thumbnail concepts", "Generate text concepts/descriptions for a thumbnail.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates text descriptions of thumbnail concepts (layout, text overlay, focal point); no image is rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(9, "Retention editing plan", "Generate an editing plan aimed at maximizing viewer retention.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text editing plan (pacing, cut points, pattern interrupts) from an input script; no video is edited.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(10, "Content calendar", "Generate an on-demand draft content calendar.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a draft content calendar as structured JSON for the requested period; not persisted unless separately saved.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(11, "Brand style matching", "Apply stored brand tone/style rules to generated copy.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Recalls stored brand tone/style rules from the Memory Agent and applies them to generated copy.",
         SCHEMA_CHECK, DB_SCOPED, audit_required=False),
    _cap(12, "CGI/motion ad planning", "Generate a text planning document for CGI/motion ad concepts.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text planning document describing CGI/motion ad concepts and shot intent; no video is rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(13, "A/B hook variations", "Generate multiple hook variations for A/B testing.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates multiple candidate hook variations as text for the caller to A/B test manually.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(14, "YouTube title pack", "Generate a set of candidate YouTube video titles.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a set of candidate YouTube titles as text; nothing is uploaded or published.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(15, "YouTube thumbnail pack", "Generate a set of candidate thumbnail concepts for YouTube.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a set of candidate thumbnail concept descriptions as text; no image is rendered or uploaded.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(16, "Script split into 8-second scenes", "Split a script into approximately 8-second scene segments.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Splits input script text into approximately 8-second scene segments for downstream video-prompt generation.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(17, "Creator asset manager", "Track references to generated content assets.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Tracks references to generated content assets (scripts, prompts, copy) in the DB-backed asset table.",
         DB_CHECK, DB_SCOPED),
    _cap(18, "Shot list generation", "Generate a shot list from a script or storyboard.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text shot list from an input script or storyboard; no filming occurs.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(19, "B-roll plan", "Generate a plan of suggested B-roll footage.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text list of suggested B-roll shots/themes tied to a script; no footage is sourced or filmed.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(20, "Music/SFX notes", "Generate suggested music mood and sound-effect cue notes.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates text notes suggesting music mood and SFX cue points for a script; no audio is sourced or rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(21, "Publishing checklist", "Generate a pre-publish checklist for a piece of content.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a pre-publish checklist (captions, thumbnail, compliance, approval status) for review. "
         "Do not publish automatically. Publishing requires approval.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(22, "Approval before publishing", "Require explicit approval before any content is marked ready to publish.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Creates an explicit approval request before any content is marked publish-ready. "
         "Do not publish automatically. Publishing requires approval.",
         AUDIT_CHECK, APPROVAL_GATED),
    _cap(23, "Competitor content analysis", "Summarize competitor content patterns from supplied input.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Summarizes competitor content patterns from input/handoff data supplied by the Browser Agent; "
         "does not scrape live sites itself.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(24, "CTA variations", "Generate multiple call-to-action variations.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates multiple candidate call-to-action lines as text.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(25, "Offer angle generation", "Generate multiple marketing offer angles.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates multiple candidate offer angles as text from a product/service brief.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(26, "Multi-platform repurposing", "Reformat existing content for other platforms' constraints.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reformats existing generated content into platform-specific variant text (length/tone/format); nothing is posted.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(27, "Instagram caption", "Generate an Instagram post caption.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates Instagram-style caption text; returned to the caller, nothing is posted to Instagram.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(28, "TikTok caption", "Generate a TikTok post caption.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates TikTok-style caption text; returned to the caller, nothing is posted to TikTok.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(29, "YouTube Shorts plan", "Generate a content plan for a YouTube Shorts video.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text plan (hook, scenes, caption) for a YouTube Shorts video; nothing is uploaded.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(30, "Facebook ad copy", "Generate Facebook ad copy.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates Facebook-style ad copy text; returned to the caller, no ad is submitted to Meta.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(31, "Google Ads creative text", "Generate Google Ads headline/description text.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates Google Ads-style headline/description text within character-limit constraints; no ad is submitted.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(32, "Landing page hero copy", "Generate hero-section copy for a landing page.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates landing-page hero headline/subheadline/CTA text; returned to the caller, no page is published.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(33, "Email campaign copy", "Generate copy for an email marketing campaign.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates email subject line and body copy as text; no email is sent.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(34, "Brand tone memory", "Read/write brand tone and style rules to durable memory.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Reads/writes brand tone and style rules via the DB-backed memory layer, scoped to the workspace.",
         DB_CHECK, DB_SCOPED),
    _cap(35, "Content idea generator", "Generate a list of candidate content ideas.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a list of candidate content ideas as text from a topic/niche brief.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(36, "Monthly content calendar", "Generate and persist a monthly content calendar record.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a monthly content calendar and persists it as a scoped calendar record for later recall.",
         DB_CHECK, DB_SCOPED),
    _cap(37, "Product launch script", "Generate a video/announcement script for a product launch.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a product-launch announcement script as text.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(38, "Explainer video outline", "Generate an outline for an explainer video.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a structured outline (problem, solution, demo, CTA) for an explainer video script.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(39, "UGC ad script", "Generate a user-generated-content style ad script.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a UGC-style ad script as text intended for a creator/actor to perform.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(40, "Testimonial ad script", "Generate a testimonial-style ad script.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a testimonial-style ad script template as text; any real customer testimonial content supplied "
         "by the caller is treated as sensitive input and is not stored beyond the request.",
         SCHEMA_CHECK, EPHEMERAL),
    _cap(41, "Before/after ad concept", "Generate a before/after style ad concept.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text before/after ad concept (framing, copy, visual beats); no image/video is rendered.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(42, "Storytelling framework", "Generate a storytelling framework/outline for a campaign.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a text storytelling framework (e.g. problem-agitate-solve) applied to the campaign brief.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(43, "Hook scoring", "Score generated hooks by heuristic engagement signals.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Scores generated hooks using a local heuristic (length, curiosity gap, specificity); no external analytics platform is called.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(44, "Creative compliance check", "Check generated copy against basic compliance/policy rules.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Runs a rule-based compliance check (banned claims, platform policy keywords) against generated copy "
         "before it reaches the publishing checklist.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(45, "Creator-to-Visual handoff", "Hand off approved creative briefs/scripts to the Visual Agent.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Hands off approved creative briefs/scripts to the Visual Agent for asset production.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(46, "Creator-to-Browser research handoff", "Hand off a research request to the Browser Agent.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Hands off a research request (e.g. competitor pages) to the Browser Agent; the Creator Agent never scrapes directly.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(47, "Creator-to-Business campaign handoff", "Hand off finalized campaign creative to the Business Agent.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Hands off finalized, approved campaign creative to the Business Agent for campaign scheduling/tracking.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(48, "Creator Agent health/dependency check", "Report Creator Agent health and configured dependencies.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports LLM provider connectivity and whether optional video-rendering/publishing adapters are configured.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(49, "Creator audit log", "Report which users/agents took which creator actions and when.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads from the audit log table filtered to creator-category events.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(50, "No auto-publishing enforcement", "Guarantee this agent never publishes content automatically.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Hard-enforces that no content is ever published automatically; every publish action requires explicit "
         "approval before execution. Do not publish automatically. Publishing requires approval.",
         PUBLISH_GATE_CHECK, APPROVAL_GATED),
]

assert len(CAPABILITIES) == 50, f"creator capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
