"""Capability data for the Security Agent (agent_key="security").

Purpose (from mission spec): Risk, approval, policy, audit, fraud, anomaly,
and permission brain.

Live MVP behavior:
- Classify/risk-score/approve/deny/log.
- Block critical actions by default.
- No risky action proceeds without approval.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "security"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Persisted to the DB-backed audit/policy tables, keyed by user_id + workspace_id; never mixed across tenants."
NOT_PERSISTED = "Not persisted; produces an in-request classification/decision without creating a new record."
AUDIT_ONLY = "Not stored as memory; written only to the audit log table for compliance traceability."
APPROVAL_GATED = "Persisted only as part of an approval-request record; sensitive payload fields redacted until resolved."
EPHEMERAL = "Held only for the lifetime of the active session/request; not persisted to durable storage."

SCHEMA_CHECK = "VerificationAgent confirms the response matches the normalized result schema."
AUDIT_CHECK = "VerificationAgent confirms a matching audit log row was written for this decision."
APPROVAL_CHECK = "VerificationAgent confirms an approval-request record exists with the expected resolved state."
DB_CHECK = "VerificationAgent confirms the expected row exists/changed in the scoped DB table for this action."
UNAVAILABLE_CHECK = "N/A while capability_status is external_dependency_required or planned; verification is skipped and surfaced as such."

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "Action classification", "Classify an incoming task/action into a risk category before it is allowed to proceed.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a rule-based classifier (action type/keyword/category match) and returns the classification synchronously.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(2, "Risk scoring", "Assign a numeric/tiered risk score to a classified action.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes a rule-based risk score from action classification, target, and requester context.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(3, "Permission checking", "Check whether the requesting user/agent has permission to perform the action.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the caller's role/permission flags against the action's required permission before allowing it to proceed.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(4, "Role access enforcement", "Enforce role-based access control across agent actions.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Compares the caller's assigned role against the action's role ACL and rejects mismatches.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(5, "Plan access enforcement", "Enforce subscription-plan-based access limits on agent actions.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the workspace's subscription plan against the action's plan requirement via subscriptions/access_control.py before allowing it.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(6, "Sensitive action approval", "Require explicit approval before any sensitive action (system_command, payment_action, file_delete, etc.) executes.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Intercepts sensitive actions and blocks execution until an approval decision is recorded.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(7, "Approval request creation", "Create a structured approval request for a sensitive action.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Writes an approval-request record with action context, requester, and risk score.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(8, "Approval decision logging", "Log the outcome (approved/denied) of an approval request.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Writes the approval decision, approver identity, and timestamp to the approval-request record.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(9, "Denial logging", "Log denied actions along with the reason for denial.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Writes a denial record with action, requester, and reason to the audit log.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(10, "Audit logs", "Provide a queryable audit trail of security-relevant events.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads from the DB-backed audit log table filtered by scoped user_id/workspace_id.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(11, "Biometric approval hook", "Accept a biometric confirmation (fingerprint/face) as an approval method.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Falls back to PIN/voice approval until a biometric hardware SDK is configured; never fakes a biometric match.",
         UNAVAILABLE_CHECK, APPROVAL_GATED, required_integrations=["biometric_hardware_sdk"]),
    _cap(12, "PIN approval hook", "Accept a PIN code as an approval method for sensitive actions.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Compares a submitted PIN against its stored hash and records the approval outcome.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(13, "Voice approval hook", "Accept a spoken voiceprint confirmation as an approval method.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Falls back to PIN approval until a voice biometric provider is configured; never fakes a voice match.",
         UNAVAILABLE_CHECK, APPROVAL_GATED, required_integrations=["voice_biometric_provider"]),
    _cap(14, "Trusted device check", "Check whether the requesting device is on the user's trusted-device list.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Compares the request's device fingerprint against the DB-backed trusted-device list.",
         DB_CHECK, DB_SCOPED),
    _cap(15, "Unknown device blocking", "Block sensitive actions originating from an unrecognized device.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Rejects the action and returns approval_required when the device fingerprint has no trusted-device match.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(16, "Payment guard", "Gate payment_action tasks behind mandatory Security Agent approval.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Intercepts every payment_action and blocks execution until explicit approval is recorded.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(17, "Banking app guard", "Apply extra scrutiny/approval to actions targeting banking or financial applications.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Flags actions targeting a known banking-app allowlist and requires approval before proceeding.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(18, "File delete protection", "Gate file_delete tasks behind mandatory approval.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Intercepts file_delete actions and blocks execution until explicit approval is recorded.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(19, "Protected folder enforcement", "Prevent write/delete actions on designated protected folders.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Rejects any action targeting a path on the protected-folder list, regardless of approval status.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(20, "Fraud detection", "Detect patterns indicative of financial fraud in a requested action.",
         Risk.HIGH, Perm.ALLOWED, Status.AVAILABLE,
         "Applies rule-based fraud heuristics (amount, recipient novelty, velocity) to flag suspicious actions for approval.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(21, "Phishing link detection", "Detect likely phishing URLs referenced in a task.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a rule-based URL/domain heuristic check (lookalike domains, known bad patterns) to flag suspicious links.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(22, "Fake invoice detection", "Detect signs of a fraudulent/fake invoice in a document or payment request.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies rule-based checks (mismatched bank details, new payee, formatting anomalies) to flag suspicious invoices.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(23, "Suspicious process detection", "Flag operating-system processes matching known-malicious or anomalous patterns.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a rule-based process-name/behavior heuristic to process data supplied by the System Agent.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(24, "Suspicious browser extension detection", "Flag browser extensions matching known-malicious or over-privileged patterns.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a rule-based extension allowlist/permission heuristic to extension data supplied by the Browser Agent.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(25, "Threat monitor", "Continuously monitor scoped activity for known threat indicators.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Polls recent scoped audit/event data against a rule-based threat-indicator list.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(26, "Anomaly detection", "Detect activity that deviates from a user/workspace's established behavior baseline.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies rule-based thresholds (time-of-day, volume, new target) against scoped historical activity.",
         SCHEMA_CHECK, NOT_PERSISTED),
    _cap(27, "Session timeout", "Automatically expire an authenticated session after inactivity.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Enforces a configurable inactivity timeout and invalidates the session token when exceeded.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(28, "Re-authentication requirement", "Require the user to re-authenticate before a sensitive action proceeds.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Blocks the action and prompts for credential re-entry when the session exceeds the re-auth threshold.",
         APPROVAL_CHECK, EPHEMERAL),
    _cap(29, "App lock", "Lock a designated app/workspace area behind an additional authentication step.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Marks the target app as locked and requires successful re-authentication to unlock.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(30, "Privacy guard", "Prevent agents from exposing private user data outside its authorized scope.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a rule-based field-level privacy filter to outbound agent responses.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(31, "Secret redaction", "Redact API keys, passwords, and other secrets from logs and responses.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a regex/pattern-based secret scanner via security/secrets_manager.py before logging or returning content.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(32, "Prevent hidden monitoring", "Prevent any agent from enabling covert screen/keystroke/microphone monitoring of the user.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Rejects any monitoring-capable action that lacks explicit, visible user consent, regardless of requester.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(33, "Prevent auto-transfer", "Prevent any agent from initiating an automatic funds transfer without explicit per-transaction approval.",
         Risk.CRITICAL, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Hard-blocks any transfer/payment action lacking an explicit, single-use approval token.",
         APPROVAL_CHECK, AUDIT_ONLY),
    _cap(34, "Prevent unsafe terminal commands", "Prevent execution of destructive or unsafe terminal/system commands.",
         Risk.CRITICAL, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Matches requested commands against a rule-based deny-list (e.g. recursive delete, disk format, permission changes) and blocks matches outright.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(35, "Emergency lock", "Immediately lock down the account/workspace on user command in a suspected compromise.",
         Risk.CRITICAL, Perm.ALLOWED, Status.AVAILABLE,
         "Suspends all agent execution and requires re-authentication for the scoped user/workspace the moment it is invoked.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(36, "Kill switch", "Immediately halt all running agent tasks system-wide or per-workspace.",
         Risk.CRITICAL, Perm.ALLOWED, Status.AVAILABLE,
         "Signals the task manager to cancel/stop all in-flight tasks for the scoped target.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(37, "Freeze automation", "Pause all scheduled/automated workflows for a user or workspace.",
         Risk.CRITICAL, Perm.ALLOWED, Status.AVAILABLE,
         "Sets a freeze flag that the Workflow Agent checks before executing any scheduled/automated run.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(38, "Per-agent policy engine", "Apply distinct security policy rules per specialized agent.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Loads and evaluates an agent-specific policy section before allowing that agent's actions.",
         SCHEMA_CHECK, DB_SCOPED, audit_required=False),
    _cap(39, "Default policy JSON loader", "Load the baseline security policy from security/policies/default_policy.json.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads and parses the default policy file at startup/on demand, falling back to conservative built-in defaults if the file is missing.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(40, "Workspace-specific policy", "Layer workspace-level policy overrides on top of the default policy.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Merges a DB-backed workspace policy record over the default policy for scoped evaluation.",
         DB_CHECK, DB_SCOPED),
    _cap(41, "User-specific policy override", "Layer user-level policy overrides on top of workspace/default policy.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Proposes the override and applies it only after Security Agent/admin approval, to prevent silent privilege escalation.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(42, "Risk heatmap dashboard", "Provide an aggregate risk-level visualization across recent actions.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Aggregates scoped risk scores from the audit log into counts/buckets for the dashboard.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(43, "Compliance/security report", "Generate a compliance/security summary report for a workspace.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Compiles scoped audit/approval/policy data into a structured report.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(44, "Security event WebSocket", "Stream real-time security events (approvals, denials, alerts) to the dashboard.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Publishes scoped security events onto the existing WebSocket channel as they occur.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(45, "Approval expiry", "Automatically expire an approval request that is not resolved within a time limit.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Marks pending approval requests as expired/denied once their TTL elapses.",
         AUDIT_CHECK, AUDIT_ONLY),
    _cap(46, "Multi-step approval chain", "Require sequential approval from multiple approvers for high-risk actions.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Tracks an ordered list of required approvers and only permits execution once every step is approved.",
         APPROVAL_CHECK, APPROVAL_GATED),
    _cap(47, "Audit export", "Export the audit log to a portable file for compliance review.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Generates a scoped audit export only after explicit approval, with sensitive fields redacted by default.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(48, "Security Agent health/dependency check", "Report Security Agent health and which optional adapters (biometric, voice) are configured.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports policy-file load status, DB connectivity, and configured approval-hook adapters.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(49, "Security test mode", "Run security checks in a simulation mode that never blocks or approves real actions.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Evaluates classification/risk/policy logic against a supplied test payload without writing audit/approval records.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(50, "Security incident summary", "Summarize a specific security incident (denials, anomalies, approvals) into a narrative report.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Compiles scoped audit/approval/anomaly records related to an incident into a structured summary.",
         SCHEMA_CHECK, NOT_PERSISTED),
]

assert len(CAPABILITIES) == 50, f"security capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
