"""Capability data for the System Agent (agent_key="system").

Purpose (from mission spec): Device/app/file/OS control with strict approval
and safe local workers.

Live MVP behavior:
- Implement safe status and preview mode.
- Real device actions only through worker adapters and approval.
- Return approval_required or external_dependency_required when not configured.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "system"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Stored in the DB-backed memory/audit tables, keyed by user_id + workspace_id; never mixed across tenants."
EPHEMERAL = "Held only for the lifetime of the active request; not persisted to durable storage."
APPROVAL_GATED = "Persisted only after explicit user/Security Agent approval; the request is logged whether approved or refused."
NOT_PERSISTED = "Not persisted; returns a live status/read result without creating a durable record."

SCHEMA_CHECK = "VerificationAgent confirms response matches the normalized result schema."
AUDIT_CHECK = "VerificationAgent confirms a matching audit log row was written for this action."
UNAVAILABLE_CHECK = "N/A while capability_status is external_dependency_required or planned; verification is skipped and surfaced as such."
FS_CHECK = "VerificationAgent confirms the target file/folder exists (or no longer exists) on disk with the expected state."
WORKER_CHECK = "VerificationAgent confirms the worker bridge reported the device action succeeded before marking the task complete."

WIN_MAC_WORKERS = ["windows_worker_agent", "mac_worker_agent"]

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "System health summary", "Report an overall summary of local system health.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes a live summary from local OS status APIs.", SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(2, "CPU/RAM/disk check", "Report current CPU, RAM, and disk utilization.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads live utilization figures from local OS status APIs.", SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(3, "Battery status", "Report current battery charge and power state, if present.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads live battery state from local OS status APIs; reports not-applicable on desktops with no battery.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(4, "Network status", "Report current network connectivity and interface state.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads live connectivity state from local OS network APIs.", SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(5, "Open app with approval", "Launch a named application on the user's device.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to actually launch the app.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(6, "Close app with approval", "Close a named running application on the user's device.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to actually close the app.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(7, "Focus app/window", "Bring a named application window to the foreground.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to change window focus; returns external_dependency_required until then.",
         WORKER_CHECK, EPHEMERAL, required_integrations=WIN_MAC_WORKERS),
    _cap(8, "Detect frozen app", "Detect whether a named application has become unresponsive.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to query process responsiveness; returns external_dependency_required until then.",
         WORKER_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=WIN_MAC_WORKERS),
    _cap(9, "Restart frozen app with approval", "Force-restart an application detected as frozen/unresponsive.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to kill and relaunch the app.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(10, "List allowed directory files", "List files within a directory the workspace has explicitly allow-listed.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Lists directory contents using local filesystem access scoped to the allow-listed path only.",
         FS_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(11, "Create file in allowed directory", "Create a new file inside an allow-listed directory.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Writes the new file to the allow-listed path using local filesystem access.", FS_CHECK, NOT_PERSISTED),
    _cap(12, "Rename file", "Rename a file within an allow-listed directory.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Renames the file in place using local filesystem access scoped to the allow-listed path.", FS_CHECK, NOT_PERSISTED),
    _cap(13, "Move file", "Move a file between allow-listed directories.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Moves the file using local filesystem access scoped to allow-listed paths.", FS_CHECK, NOT_PERSISTED),
    _cap(14, "Copy file", "Copy a file within or between allow-listed directories.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Copies the file using local filesystem access scoped to allow-listed paths.", FS_CHECK, NOT_PERSISTED),
    _cap(15, "Delete file only with backup and approval", "Delete a file, but only after taking a backup copy and receiving explicit approval.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Creates a backup copy and requests explicit approval before deleting; refuses deletion without both.",
         FS_CHECK, APPROVAL_GATED),
    _cap(16, "Compress folder", "Compress a folder into an archive file.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Creates a zip archive of the folder using local filesystem access.", FS_CHECK, NOT_PERSISTED),
    _cap(17, "Organize downloads", "Sort files in a downloads folder into categorized subfolders.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Moves files into type-based subfolders within the allow-listed downloads directory.", FS_CHECK, NOT_PERSISTED),
    _cap(18, "Protected folder rules", "Enforce a list of protected folders that file operations may never target.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks every file operation's target path against a protected-folder rule set before executing.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(19, "Safe OS command preview", "Show what an OS command would do without executing it.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Parses and describes the command's effect using a local safe-command analyzer; never executes it.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(20, "Run approved safe OS command", "Execute an OS command that has passed the safe-command check and been approved.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to execute the command on the user's device.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(21, "Block dangerous terminal commands", "Refuse to run terminal commands matched against a dangerous-command blocklist.",
         Risk.LOW, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Checks every command against a local dangerous-command blocklist and refuses execution on a match.",
         AUDIT_CHECK, NOT_PERSISTED),
    _cap(22, "Port/service status check", "Report whether a named local port/service is active.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Checks local port/service state using standard OS networking APIs.", SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
    _cap(23, "Start safe local service with approval", "Start a named local service that has been marked safe to run.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to start the service.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(24, "Stop service with approval", "Stop a named running local service.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to stop the service.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(25, "Control volume adapter", "Adjust the device's system audio volume.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to change system volume; returns external_dependency_required until then.",
         WORKER_CHECK, EPHEMERAL, required_integrations=WIN_MAC_WORKERS),
    _cap(26, "Control brightness adapter", "Adjust the device's display brightness.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to change display brightness; returns external_dependency_required until then.",
         WORKER_CHECK, EPHEMERAL, required_integrations=WIN_MAC_WORKERS),
    _cap(27, "WiFi status adapter", "Report the device's current WiFi connection state.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to read WiFi adapter state; returns external_dependency_required until then.",
         WORKER_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=WIN_MAC_WORKERS),
    _cap(28, "Bluetooth status adapter", "Report the device's current Bluetooth connection state.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to read Bluetooth adapter state; returns external_dependency_required until then.",
         WORKER_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=WIN_MAC_WORKERS),
    _cap(29, "Lock screen with approval", "Lock the device's screen.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to lock the screen.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(30, "Sleep/restart/shutdown requires approval", "Put the device to sleep, restart it, or shut it down.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to perform the power action.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(31, "Keyboard shortcut automation", "Send a predefined keyboard shortcut to the active application.",
         Risk.HIGH, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a configured OS worker bridge to inject the keystroke; returns external_dependency_required until then.",
         WORKER_CHECK, EPHEMERAL, required_integrations=WIN_MAC_WORKERS),
    _cap(32, "Typing automation with approval", "Type arbitrary text into the active application on the user's behalf.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to inject keystrokes.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(33, "Mouse click automation with approval", "Perform mouse clicks at specified screen coordinates on the user's behalf.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to inject mouse events.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(34, "Scroll/drag automation with approval", "Perform mouse scroll/drag gestures on the user's behalf.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to inject scroll/drag events.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(35, "Macro recorder", "Record a sequence of intended actions as a reusable macro definition.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Stores the recorded action sequence as data in the DB-backed memory table; does not execute anything while recording.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(36, "Macro replay with approval", "Replay a previously recorded macro's actions on the user's device.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns approval_required and, once approved, requires a configured OS worker bridge to replay each recorded action.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=WIN_MAC_WORKERS),
    _cap(37, "Screen-aware automation handoff to Visual Agent", "Hand off a task requiring screen understanding to the Visual Agent before automating.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Packages the automation request and routes it to the Visual Agent for screen analysis before any action runs.",
         SCHEMA_CHECK, EPHEMERAL),
    _cap(38, "Notification reading with permission", "Read the device's current notifications, only with explicit permission.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires explicit permission and a configured OS/mobile worker bridge to read notifications; refuses otherwise.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=["windows_worker_agent", "android_worker_bridge"]),
    _cap(39, "Draft message reply with approval", "Draft a suggested reply to a message, without sending it.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Generates a draft reply as text for the user to review; never sends it automatically.",
         SCHEMA_CHECK, EPHEMERAL),
    _cap(40, "Call answer/reject with permission", "Answer or reject an incoming call on the user's device, only with explicit permission.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires explicit permission and a configured mobile worker bridge to answer/reject calls; refuses otherwise.",
         WORKER_CHECK, APPROVAL_GATED, required_integrations=["android_worker_bridge", "ios_shortcuts_bridge"]),
    _cap(41, "Windows worker bridge", "Connect to the Windows worker node for real device actions on Windows.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Reports connection status; real device actions stay unavailable until the Windows worker node is paired and configured.",
         WORKER_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["windows_worker_agent"]),
    _cap(42, "Mac worker bridge", "Connect to the Mac worker node for real device actions on macOS.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Reports connection status; real device actions stay unavailable until the Mac worker node is paired and configured.",
         WORKER_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["mac_worker_agent"]),
    _cap(43, "Android Accessibility worker bridge", "Connect to the Android Accessibility-service worker for real device actions on Android.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Reports connection status; real device actions stay unavailable until the Android Accessibility worker is paired and configured.",
         WORKER_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["android_worker_bridge"]),
    _cap(44, "iOS Shortcuts bridge", "Connect to an iOS Shortcuts-based worker for real device actions on iOS.",
         Risk.LOW, Perm.ALLOWED, Status.PLANNED,
         "No iOS worker client is implemented yet (see apps/worker_nodes/ios/ios_client_plan.md); returns a planned response.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ios_shortcuts_bridge"]),
    _cap(45, "Smart device routing", "Route a command to a connected smart-home/IoT device.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a smart-device hub integration is configured.",
         WORKER_CHECK, EPHEMERAL, required_integrations=["smart_device_hub_integration"]),
    _cap(46, "Public/private mode switching", "Toggle between public and private operating modes for output visibility.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Flips a per-session mode flag that governs how much detail is shown/spoken.", SCHEMA_CHECK, EPHEMERAL),
    _cap(47, "Banking app restricted mode", "Restrict automation from targeting banking/finance applications.",
         Risk.HIGH, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a local rule set that refuses automation targeting apps matched against a banking/finance denylist.",
         AUDIT_CHECK, NOT_PERSISTED),
    _cap(48, "File backup before risky operations", "Automatically back up a file before performing a risky operation on it.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Creates a timestamped local backup copy before the risky file operation proceeds.", FS_CHECK, NOT_PERSISTED),
    _cap(49, "Action proof handoff to Verification Agent", "Hand off a completed system action's result to the Verification Agent as proof.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Packages the action's before/after state and forwards it to the Verification Agent.", AUDIT_CHECK, EPHEMERAL),
    _cap(50, "System Agent health/dependency check", "Report System Agent health and which worker bridges/adapters are configured.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports process health plus whether Windows/Mac/Android/iOS worker bridges are configured.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
]

assert len(CAPABILITIES) == 50, f"system capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
