"""Capability data for the Verification Agent (agent_key="verification").

Purpose (from mission spec): Confirm task results with state checks, command
output, screenshots, validation, retries, and proof.

Live MVP behavior:
- Verify result schema, command output, file existence, endpoint response.
- Screenshot/OCR only if configured.
- Known adapter gap: VerificationAgent.verify_task takes context + task_payload
  as separate arguments, not a single combined dict; this is a real, existing
  mismatch being fixed elsewhere, not something this data file papers over.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "verification"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Persisted to the DB-backed memory/audit table, keyed by user_id + workspace_id; never mixed across tenants."
NOT_PERSISTED = "Not persisted; produces an in-request check result without creating a durable record."
AUDIT_ONLY = "Not stored as memory; written only to the audit log table for compliance traceability."
APPROVAL_GATED = "Persisted only after explicit consent/approval; sensitive proof payloads redacted until approved."
EPHEMERAL = "Held only for the lifetime of the active check/request; not persisted to durable storage."

UNAVAILABLE_CHECK = "N/A while capability_status is external_dependency_required; verification is skipped and surfaced as such."

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "Verify structured result schema", "Validate that an agent's task result matches the required {success, message, data, error, metadata} schema.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Runs a JSON-schema/structural check against the returned dict and flags missing/mistyped fields.",
         "Self-verified: the schema checker's own pass/fail output is what is returned.", NOT_PERSISTED, audit_required=False),
    _cap(2, "Verify API endpoint response", "Confirm a given API endpoint returns the expected status code/response shape.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Issues a real HTTP request to the endpoint and checks status code and response schema.",
         "Confirmed directly by the HTTP response received; no separate check needed.", NOT_PERSISTED, audit_required=False),
    _cap(3, "Verify server port active", "Confirm a given host:port is accepting connections.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Attempts a real TCP connection to the port and reports open/closed.",
         "Confirmed directly by the socket connection result.", NOT_PERSISTED, audit_required=False),
    _cap(4, "Verify file exists", "Confirm a file exists at the expected path.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the filesystem path with a real os.path.exists/stat call.",
         "Confirmed directly by the filesystem check result.", NOT_PERSISTED, audit_required=False),
    _cap(5, "Verify folder exists", "Confirm a folder/directory exists at the expected path.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the filesystem path with a real os.path.isdir call.",
         "Confirmed directly by the filesystem check result.", NOT_PERSISTED, audit_required=False),
    _cap(6, "Verify file modified", "Confirm a file's modification timestamp/hash changed as expected.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Compares the file's mtime/content hash before and after the action.",
         "Confirmed directly by comparing the captured before/after mtime or content hash.", EPHEMERAL, audit_required=False),
    _cap(7, "Verify backup created", "Confirm a backup file/snapshot was created for a given source.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks that a new backup artifact exists and its size/timestamp is plausible.",
         "Confirmed directly by the filesystem/snapshot existence check.", DB_SCOPED),
    _cap(8, "Verify app opened", "Confirm a desktop/mobile app actually launched.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks process list / window state supplied by the System Agent for the target app.",
         "Confirmed by cross-checking System Agent process/window state.", NOT_PERSISTED, audit_required=False),
    _cap(9, "Verify app closed", "Confirm a desktop/mobile app actually terminated.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks process list / window state supplied by the System Agent for the target app.",
         "Confirmed by cross-checking System Agent process/window state.", NOT_PERSISTED, audit_required=False),
    _cap(10, "Verify app focused", "Confirm a target app window is the active/focused window.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the active-window state supplied by the System Agent.",
         "Confirmed by cross-checking System Agent active-window state.", NOT_PERSISTED, audit_required=False),
    _cap(11, "Verify browser URL loaded", "Confirm the browser navigated to the expected URL.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the Browser Agent's reported current URL against the expected URL.",
         "Confirmed by cross-checking Browser Agent navigation state.", NOT_PERSISTED, audit_required=False),
    _cap(12, "Verify page title", "Confirm a loaded page's title matches expectations.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the Browser Agent's reported page title against the expected value/pattern.",
         "Confirmed by cross-checking Browser Agent page metadata.", NOT_PERSISTED, audit_required=False),
    _cap(13, "Verify page content", "Confirm a loaded page contains expected text/content.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the Browser Agent's extracted page text for the expected content/pattern.",
         "Confirmed by cross-checking Browser Agent extracted page content.", NOT_PERSISTED, audit_required=False),
    _cap(14, "Verify build passed", "Confirm a code build completed without errors.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Parses the real build command's exit code and output for error markers.",
         "Confirmed directly by the build process exit code and captured output.", DB_SCOPED),
    _cap(15, "Verify tests passed", "Confirm an automated test run completed with all tests passing.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Parses the real test runner's exit code and summary output for pass/fail counts.",
         "Confirmed directly by the test runner exit code and summary output.", DB_SCOPED),
    _cap(16, "Verify command output", "Confirm a shell command's output matches an expected pattern.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Runs/receives the real command output and matches it against the expected pattern.",
         "Confirmed directly by the captured stdout/stderr and exit code.", NOT_PERSISTED, audit_required=False),
    _cap(17, "Screenshot verification adapter", "Verify an action's outcome by comparing a captured screenshot to an expected state.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a screenshot capture engine is configured; never fabricates a visual match.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["screenshot_capture_engine"]),
    _cap(18, "OCR success detection adapter", "Verify success/failure by OCR-reading on-screen confirmation text.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an OCR engine is configured; never fabricates recognized text.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ocr_engine"]),
    _cap(19, "UI element verification adapter", "Verify a specific UI element is present/changed as expected.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Delegates to the Visual Agent's UI map when configured; otherwise returns external_dependency_required.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["visual_agent_ui_map"]),
    _cap(20, "Error screen detection", "Detect whether the current app/page state shows an error screen/message.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Matches captured page text/system output against a rule-based error-pattern list.",
         "Confirmed directly by the matched error-pattern result.", NOT_PERSISTED, audit_required=False),
    _cap(21, "Multi-step workflow validation", "Verify that every step in a multi-step workflow completed successfully in order.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks each step's recorded result against its expected postcondition in sequence.",
         "Confirmed directly by aggregating each step's individual verification result.", DB_SCOPED),
    _cap(22, "Failed step detection", "Identify which specific step(s) in a workflow failed.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Diffs expected vs actual step results to isolate the first failing step.",
         "Confirmed directly by the per-step verification results.", DB_SCOPED),
    _cap(23, "Retry safe failed steps", "Automatically retry a failed step when the step is classified as safe to retry.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Retries only steps tagged non-sensitive/idempotent, up to the configured retry limit.",
         "Confirmed by re-running the step's own verification check after the retry.", DB_SCOPED),
    _cap(24, "Never retry sensitive actions", "Prevent automatic retry of any action classified as sensitive, even after failure.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Hard-blocks auto-retry for sensitive-flagged steps and surfaces the failure for manual/approved re-run instead.",
         "Confirmed directly by the retry-eligibility check refusing to re-invoke the sensitive step.", AUDIT_ONLY),
    _cap(25, "Proof screenshot capture with permission", "Capture a screenshot as proof of task completion, only with explicit permission.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires an explicit consent flag and a configured capture engine; returns external_dependency_required otherwise.",
         UNAVAILABLE_CHECK, APPROVAL_GATED, required_integrations=["screenshot_capture_engine"]),
    _cap(26, "Proof log collection", "Collect relevant log excerpts as proof of task completion.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Gathers the real captured stdout/stderr/log lines produced during task execution.",
         "Confirmed directly by the presence of the collected log content.", DB_SCOPED),
    _cap(27, "Proof command output collection", "Collect command output as proof of task completion.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Gathers the real captured command output produced during task execution.",
         "Confirmed directly by the presence of the collected command output.", DB_SCOPED),
    _cap(28, "Confidence scoring", "Assign a confidence score to a verification result based on how much evidence supports it.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes a rule-based score from how many independent checks (schema, output, state) agreed.",
         "Self-verified: the score is derived transparently from the underlying check results returned alongside it.", NOT_PERSISTED, audit_required=False),
    _cap(29, "Partial success detection", "Detect when a task achieved some but not all of its expected outcomes.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Compares each expected outcome individually and reports a partial-success state when only some match.",
         "Confirmed directly by the per-outcome comparison results.", NOT_PERSISTED, audit_required=False),
    _cap(30, "Visual regression check adapter", "Detect unintended visual changes by comparing before/after screenshots.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a visual regression engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["visual_regression_engine"]),
    _cap(31, "Deployment verification", "Confirm a deployment completed and the deployed service is healthy.",
         Risk.HIGH, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the real deployment command's exit code plus a post-deploy health-endpoint probe.",
         "Confirmed directly by the deployment exit code and health-check response.", DB_SCOPED),
    _cap(32, "Mobile/emulator state check adapter", "Verify state/outcomes on a mobile device or emulator.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a mobile/emulator bridge (per apps/worker_nodes/android) is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["mobile_emulator_bridge"]),
    _cap(33, "Download integrity check", "Confirm a downloaded file is complete and matches its expected checksum/size.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Computes a real file hash/size and compares against the expected value when provided.",
         "Confirmed directly by the computed checksum/size comparison.", NOT_PERSISTED, audit_required=False),
    _cap(34, "Completion report", "Produce a structured report summarizing what was verified and the outcome.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Compiles all individual check results for the task into one structured report.",
         "Self-verified: the report is a direct compilation of already-confirmed check results.", DB_SCOPED),
    _cap(35, "Verification memory save", "Persist verification outcomes for later recall/pattern analysis.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes the verification result to the DB-backed memory table via the Memory Agent bridge.",
         "Confirmed by re-reading back the saved row.", DB_SCOPED),
    _cap(36, "Verification pattern recall", "Recall past verification outcomes for similar tasks to inform confidence.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Queries scoped verification history from the Memory Agent.",
         "Confirmed directly by the returned historical records.", DB_SCOPED, audit_required=False),
    _cap(37, "Verification thresholds", "Define the pass/fail confidence threshold used to accept a verification result.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads a configurable threshold (default or per-workspace) and applies it to the computed confidence score.",
         "Self-verified: threshold application is deterministic and shown alongside the result.", DB_SCOPED, audit_required=False),
    _cap(38, "Retry limit enforcement", "Cap the number of automatic retries for a failed, retry-eligible step.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Tracks retry count per step and stops auto-retry once the configured limit is reached.",
         "Confirmed directly by the tracked retry counter.", EPHEMERAL, audit_required=False),
    _cap(39, "Timeout enforcement", "Fail a verification check that does not complete within a configured time limit.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a real wall-clock timeout to each check and marks it failed/unknown on expiry.",
         "Confirmed directly by the elapsed-time measurement.", EPHEMERAL, audit_required=False),
    _cap(40, "Verification audit log", "Record every verification decision to the audit log.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes each verification outcome to the DB-backed audit log table.",
         "Confirmed by re-reading back the written audit row.", DB_SCOPED),
    _cap(41, "Verification payload builder", "Build the normalized payload MasterAgent passes into the Verification Agent for a task.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Assembles context + task_payload fields from core/verification_bridge.py into the expected structure.",
         "Self-verified: the builder's own schema check confirms required fields are present.", NOT_PERSISTED, audit_required=False),
    _cap(42, "MasterAgent verification bridge", "Connect MasterAgent's task-completion flow to the Verification Agent's checks.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Invokes the Verification Agent via core/verification_bridge.py after execution and returns its structured result; "
         "note VerificationAgent.verify_task currently takes context and task_payload as separate arguments rather than one "
         "combined dict, a known real adapter gap some call sites may not yet handle correctly.",
         "Confirmed directly by inspecting the returned verification result and bridge call success.", NOT_PERSISTED),
    _cap(43, "Code Agent verification", "Verify Code Agent task outcomes (build, test, file changes).",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Runs build/test/file-existence checks scoped to the Code Agent's reported changes.",
         "Confirmed directly by build/test exit codes and file checks.", DB_SCOPED),
    _cap(44, "Browser Agent verification", "Verify Browser Agent task outcomes (navigation, page state).",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Cross-checks the Browser Agent's reported URL/title/content against the expected outcome.",
         "Confirmed directly by Browser Agent state comparison.", NOT_PERSISTED, audit_required=False),
    _cap(45, "System Agent verification", "Verify System Agent task outcomes (app state, file operations).",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Cross-checks System Agent reported process/file state against the expected outcome.",
         "Confirmed directly by System Agent state comparison.", NOT_PERSISTED),
    _cap(46, "Workflow Agent verification", "Verify Workflow Agent task outcomes (pipeline run results).",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Cross-checks Workflow Agent run logs/step results against the expected pipeline outcome.",
         "Confirmed directly by Workflow Agent run-log comparison.", DB_SCOPED),
    _cap(47, "Finance safe verification", "Verify Finance Agent outcomes with extra safeguards, never confirming a real transaction that wasn't explicitly approved.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Cross-checks Finance Agent results against the approval record and rejects verification of any unapproved real transaction claim.",
         "Confirmed directly by cross-referencing the Security Agent approval record.", APPROVAL_GATED),
    _cap(48, "Security decision verification", "Verify that a Security Agent approval/denial decision was correctly applied to the underlying action.",
         Risk.HIGH, Perm.ALLOWED, Status.AVAILABLE,
         "Cross-checks the executed action against the recorded approval decision to confirm they match.",
         "Confirmed directly by comparing the audit log's approval decision to the action outcome.", AUDIT_ONLY),
    _cap(49, "Verification Agent health/dependency check", "Report Verification Agent health and which optional adapters (screenshot, OCR, visual regression) are configured.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports which check types are available today versus external_dependency_required.",
         "Self-verified: reports its own adapter configuration state directly.", NOT_PERSISTED, audit_required=False),
    _cap(50, "Verification dashboard status", "Provide aggregate verification metrics (pass rate, common failures) for the dashboard.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes counts/aggregates from scoped verification history.",
         "Confirmed directly by the underlying aggregate query.", NOT_PERSISTED, audit_required=False),
]

assert len(CAPABILITIES) == 50, f"verification capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
