"""Capability data for the Visual Agent (agent_key="visual").

Purpose (from mission spec): Screen/image/video understanding, OCR, UI
mapping, privacy filtering, and visual validation.

Live MVP behavior:
- Analyze provided/uploaded image metadata and basic structure if available.
- OCR/screenshot capture only if configured.
- Return external_dependency_required for unavailable visual capture.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "visual"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Persisted to the DB-backed memory table via the Memory Agent bridge, keyed by user_id + workspace_id."
NOT_PERSISTED = "Not persisted; operates on the supplied image/screenshot without creating a durable record."
APPROVAL_GATED = "Persisted only after explicit consent/approval; raw sensitive imagery is redacted or discarded until approved."
AUDIT_ONLY = "Not stored as memory; written only to the audit log table for compliance traceability."

SCHEMA_CHECK = "VerificationAgent confirms the response matches the normalized result schema."
UNAVAILABLE_CHECK = "N/A while capability_status is external_dependency_required; verification is skipped and surfaced as such."

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "Screenshot understanding", "Analyze a captured screenshot to describe its contents.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image/vision analysis engine is configured; does not fabricate a description.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine"]),
    _cap(2, "Image understanding", "Analyze an uploaded image to describe its contents.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image/vision analysis engine is configured; does not fabricate a description.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine"]),
    _cap(3, "OCR text extraction adapter", "Extract text content from an image via OCR.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an OCR engine (e.g. Tesseract) is configured; never fabricates recognized text.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ocr_engine"]),
    _cap(4, "UI button detection", "Detect clickable button elements within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(5, "UI input detection", "Detect text-input fields within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(6, "Form field detection", "Detect form fields and their labels within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model plus OCR is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model", "ocr_engine"]),
    _cap(7, "Dashboard layout mapping", "Map the layout/regions of a dashboard screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(8, "Error popup detection", "Detect error popups/dialogs within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until OCR and UI detection are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ocr_engine", "ui_element_detection_model"]),
    _cap(9, "Toast/modal detection", "Detect toast notifications and modal dialogs within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(10, "Video frame extraction", "Extract individual frames from a screen-recording video.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a video processing engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["video_processing_engine"]),
    _cap(11, "Screen recording workflow timeline", "Reconstruct a chronological action timeline from a screen recording.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a video processing engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["video_processing_engine"]),
    _cap(12, "Click detection in videos", "Detect click events within a screen-recording video.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a video processing engine and UI detection model are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["video_processing_engine", "ui_element_detection_model"]),
    _cap(13, "Scroll detection in videos", "Detect scroll events within a screen-recording video.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a video processing engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["video_processing_engine"]),
    _cap(14, "Visual workflow learner", "Learn a repeatable workflow by observing a sequence of screenshots/recordings.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until video processing and UI detection are configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, required_integrations=["video_processing_engine", "ui_element_detection_model"]),
    _cap(15, "Element bounds for automation", "Return pixel-coordinate bounds of a UI element for downstream automation clicks.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(16, "Before/after screenshot compare", "Compare two screenshots to detect what changed.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Computes a real pixel/structural diff between the two supplied images using local image-diff logic.",
         "VerificationAgent confirms the diff regions reported are non-empty/consistent with the reported change.", NOT_PERSISTED, audit_required=False),
    _cap(17, "Landing page visual audit", "Audit a landing page screenshot for visual quality issues.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image analysis engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine"]),
    _cap(18, "Design spacing feedback", "Give feedback on spacing/whitespace consistency in a design screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(19, "Alignment feedback", "Give feedback on element alignment in a design screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(20, "Color contrast checks", "Check text/background color-contrast ratios against WCAG guidelines.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Computes real WCAG contrast ratios from supplied foreground/background color values or sampled pixels.",
         "VerificationAgent recomputes the contrast ratio from the same inputs and compares.", NOT_PERSISTED, audit_required=False),
    _cap(21, "Accessibility visual hints", "Surface basic accessibility hints (missing alt text markers, low contrast) from available screenshot metadata.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Applies rule-based accessibility heuristics to whatever structural/metadata info is available.",
         "VerificationAgent confirms hints match the rule-based checklist applied.", NOT_PERSISTED, audit_required=False),
    _cap(22, "Sensitive data detection", "Detect sensitive data (card numbers, passwords, IDs) visible in a screenshot.",
         Risk.HIGH, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an OCR engine is configured; never assumes text content.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, required_integrations=["ocr_engine"]),
    _cap(23, "Visual privacy redaction", "Redact detected sensitive regions from a screenshot before storage/sharing.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until OCR/detection is configured; never stores an unredacted sensitive image.",
         UNAVAILABLE_CHECK, APPROVAL_GATED, required_integrations=["ocr_engine", "image_analysis_engine"]),
    _cap(24, "App screen maps", "Maintain a generic map of an application's known screens/states.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(25, "Chrome screen map", "Maintain a known screen map for the Chrome browser UI.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(26, "VS Code screen map", "Maintain a known screen map for the VS Code UI.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(27, "WordPress screen map", "Maintain a known screen map for the WordPress admin UI.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(28, "Google Ads screen map", "Maintain a known screen map for the Google Ads UI.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(29, "Google Maps card detection", "Detect Google Maps result/business cards within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model and OCR are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model", "ocr_engine"]),
    _cap(30, "Mobile screen understanding", "Analyze a mobile device screenshot to describe its contents.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image analysis engine and mobile bridge are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine", "mobile_emulator_bridge"]),
    _cap(31, "Emulator screen understanding", "Analyze an Android/iOS emulator screenshot to describe its contents.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image analysis engine and mobile/emulator bridge are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine", "mobile_emulator_bridge"]),
    _cap(32, "Annotation/report screenshots", "Produce an annotated screenshot (labels, arrows) for a report, given already-known regions.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Draws provided annotation coordinates onto the supplied image using local image-drawing logic.",
         "VerificationAgent confirms the output image dimensions/annotation count match the request.", DB_SCOPED, audit_required=False),
    _cap(33, "Draw boxes around elements", "Draw bounding boxes around given UI element coordinates on an image.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Draws the supplied bounding-box coordinates onto the image using local image-drawing logic.",
         "VerificationAgent confirms box count/coordinates in the output match the input.", NOT_PERSISTED, audit_required=False),
    _cap(34, "Visual validation handoff", "Hand off a visual state/result to the Verification Agent for confirmation.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Packages the visual result into the Verification Agent's expected payload and forwards it.",
         "Confirmed by the Verification Agent's own acceptance of the payload schema.", NOT_PERSISTED, audit_required=False),
    _cap(35, "Visual error routing to Code Agent", "Route a detected UI error state to the Code Agent for investigation.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Forwards the detected error context/screenshot reference to the Code Agent's task queue.",
         "Confirmed by the Code Agent's task-received acknowledgment.", DB_SCOPED),
    _cap(36, "Visual privacy policy enforcement", "Block screenshot/image capture of designated private screens/apps.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Checks capture requests against a rule-based denylist (banking apps, password managers) and refuses matching captures.",
         "VerificationAgent confirms no image artifact exists for a blocked request.", AUDIT_ONLY),
    _cap(37, "Screenshot consent enforcement", "Require explicit user consent before capturing any screenshot.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Rejects capture requests lacking an explicit consent flag on the task.",
         "VerificationAgent confirms the consent flag was present before any capture record exists.", AUDIT_ONLY),
    _cap(38, "Visual memory save", "Persist visual analysis results (not raw sensitive imagery) to memory.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes the structured analysis result to the DB-backed memory table via the Memory Agent bridge.",
         "Confirmed by re-reading back the saved row.", DB_SCOPED),
    _cap(39, "Repeated layout recognition", "Recognize when a screenshot's layout matches a previously seen/stored layout.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Compares structural fingerprints of the current screenshot against stored layout fingerprints in memory.",
         "VerificationAgent confirms the matched fingerprint ID exists in memory.", DB_SCOPED, audit_required=False),
    _cap(40, "UI confidence scoring", "Assign a confidence score to a detected UI element/region.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes a rule-based score from detection-adapter confidence plus contextual heuristics.",
         "Self-verified: score is derived transparently and returned alongside the detection result.", NOT_PERSISTED, audit_required=False),
    _cap(41, "Table/card detection", "Detect tabular/card-style content regions within a screenshot.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a UI element detection model is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["ui_element_detection_model"]),
    _cap(42, "Logo/brand asset detection", "Detect logo/brand assets within an image.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image analysis engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine"]),
    _cap(43, "Creative image analysis", "Analyze a marketing creative image for composition/content.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image analysis engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["image_analysis_engine"]),
    _cap(44, "Ad creative review", "Review an ad creative for policy/quality issues before publishing.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an image analysis engine is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, required_integrations=["image_analysis_engine"]),
    _cap(45, "Screenshot proof packaging", "Package a captured screenshot with metadata as verifiable proof of completion, only with permission.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Bundles an already-captured, consented screenshot with timestamp/context metadata.",
         "VerificationAgent confirms the proof package's metadata matches the originating task.", APPROVAL_GATED),
    _cap(46, "Image metadata extraction", "Extract basic metadata (dimensions, format, EXIF) from a supplied image.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads real image metadata using local image-library parsing (dimensions, format, EXIF if present).",
         "VerificationAgent confirms extracted metadata matches the file's actual header data.", NOT_PERSISTED, audit_required=False),
    _cap(47, "Redacted proof export", "Export a proof screenshot with sensitive regions redacted, only after approval.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Applies known redaction regions and exports only after explicit approval; refuses export of unredacted sensitive images.",
         "VerificationAgent confirms the exported file excludes the flagged sensitive regions.", APPROVAL_GATED),
    _cap(48, "Visual Agent health/dependency check", "Report Visual Agent health and which optional adapters (OCR, vision, video) are configured.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports which visual capabilities are available today versus external_dependency_required.",
         "Self-verified: reports its own adapter configuration state directly.", NOT_PERSISTED, audit_required=False),
    _cap(49, "Visual task audit log", "Record every visual-analysis task (not raw imagery) to the audit log.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes a scoped audit record (task type, consent flag, outcome) to the DB-backed audit log table.",
         "Confirmed by re-reading back the written audit row.", AUDIT_ONLY),
    _cap(50, "Visual-to-System automation bridge", "Hand off detected UI element coordinates to the System Agent to drive an automated click/input.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Forwards validated element bounds to the System Agent's automation queue; does not perform system-level input itself.",
         "Confirmed by the System Agent's task-received acknowledgment and its own action verification.", NOT_PERSISTED),
]

assert len(CAPABILITIES) == 50, f"visual capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
