"""Capability data for the Voice Agent (agent_key="voice").

Purpose (from mission spec): Speaking, listening, STT, TTS, multilingual
conversation, audio routing, and voice-controlled task execution.

Live MVP behavior:
- Accept text command now. Accept audio only if configured.
- If STT/TTS provider missing, return external_dependency_required.
- Route transcribed command to MasterAgent.
- Never always-listen without explicit enabled config.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "voice"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Stored in the DB-backed memory table, keyed by user_id + workspace_id; never mixed across tenants."
EPHEMERAL = "Held only for the lifetime of the active session/turn; not persisted to durable storage."
APPROVAL_GATED = "Persisted only after explicit user/Security Agent approval; sensitive payloads redacted until approved."
NOT_PERSISTED = "Not persisted; operates on transient audio/text without creating a durable record."

SCHEMA_CHECK = "VerificationAgent confirms response matches the normalized result schema."
DB_CHECK = "VerificationAgent confirms the expected row exists/changed in the memory table for the scoped user_id/workspace_id."
AUDIT_CHECK = "VerificationAgent confirms a matching audit log row was written for this action."
UNAVAILABLE_CHECK = "N/A while capability_status is external_dependency_required or planned; verification is skipped and surfaced as such."
CONFIG_CHECK = "VerificationAgent confirms the reported adapter/config state matches the actual configured integration."

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "Push-to-talk command capture", "Capture audio while the user holds a push-to-talk control and forward it for transcription.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Accepts a typed command today; audio capture returns external_dependency_required until an audio input worker and STT provider are configured.",
         CONFIG_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["audio_input_worker", "stt_provider_api_key"]),
    _cap(2, 'Wake word detection for "William"', 'Continuously listen for the default wake word "William" to begin a command.',
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Wake-word listening stays off until a wake-word engine is configured; text commands work without it.",
         CONFIG_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["wake_word_engine", "audio_input_worker"]),
    _cap(3, "Custom wake phrase profiles", "Let a user define an alternate wake phrase in place of the default.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Stores the requested phrase text in the DB now; live phrase detection requires a configured wake-word engine.",
         CONFIG_CHECK, DB_SCOPED, required_integrations=["wake_word_engine"]),
    _cap(4, "Always-listening idle mode with privacy disabled by default", "Optional continuous-listening idle mode that stays off unless explicitly enabled.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.APPROVAL_REQUIRED,
         "Refuses to enable continuous listening unless the user explicitly opts in via an approved config change.",
         AUDIT_CHECK, NOT_PERSISTED, required_integrations=["wake_word_engine", "audio_input_worker"]),
    _cap(5, "No private audio storage by default", "Guarantee that raw audio is never written to durable storage unless explicitly approved.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Enforces a hard guard that discards captured audio buffers after transcription instead of persisting them.",
         AUDIT_CHECK, NOT_PERSISTED),
    _cap(6, "Streaming speech-to-text", "Transcribe spoken audio to text incrementally as the user speaks.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a streaming STT provider is configured; text input works today.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["stt_provider_api_key"]),
    _cap(7, "Offline STT fallback adapter", "Fall back to a local/offline speech-to-text model when no cloud STT provider is reachable.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an offline STT model is bundled/configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["offline_stt_model"]),
    _cap(8, "Text-to-speech response", "Speak the assistant's reply aloud instead of only returning text.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns the reply as text now; audio playback requires a configured TTS provider.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["tts_provider_api_key"]),
    _cap(9, "Streaming TTS", "Begin speaking a reply before the full response text has finished generating.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a streaming-capable TTS provider is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["tts_provider_api_key"]),
    _cap(10, "Interrupt TTS when user speaks", "Stop the assistant's speech output as soon as the user starts talking.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Requires a live STT+TTS pipeline to detect barge-in; returns external_dependency_required until both are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["stt_provider_api_key", "tts_provider_api_key"]),
    _cap(11, "Smart silence detection", "Detect when the user has finished speaking using voice-activity detection.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a voice-activity-detection adapter is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["voice_activity_detection_adapter"]),
    _cap(12, "Noise suppression adapter", "Reduce background noise in captured audio before transcription.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a noise-suppression SDK is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["noise_suppression_sdk"]),
    _cap(13, "Echo cancellation adapter", "Remove echo/feedback from captured audio when speaker and mic are on the same device.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an echo-cancellation SDK is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["echo_cancellation_sdk"]),
    _cap(14, "Whisper input detection", "Recognize when the user is speaking at whisper volume and adapt capture accordingly.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until the STT provider's low-volume/whisper mode is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["stt_provider_api_key"]),
    _cap(15, "Whisper response mode", "Reply at a quieter, whisper-like TTS volume/tone when appropriate.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a TTS provider supporting a low-volume voice style is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["tts_provider_api_key"]),
    _cap(16, "Roman Urdu + English mixed command parsing", "Parse commands that mix Roman Urdu and English in the same sentence.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Parses the already-received text command using rule-based mixed-language tokenization.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(17, "Urdu understanding", "Understand commands and questions written in Urdu.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Interprets the received text command in Urdu using the core language-understanding pipeline.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(18, "Hindi understanding", "Understand commands and questions written in Hindi.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Interprets the received text command in Hindi using the core language-understanding pipeline.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(19, "Arabic understanding", "Understand commands and questions written in Arabic.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Interprets the received text command in Arabic using the core language-understanding pipeline.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(20, "Reply in same detected language", "Respond in whichever language the user's command was detected in.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Detects the input language from text and formats the reply in that same language.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(21, "Real-time translation mode", "Translate spoken/typed input between two languages in real time.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Text-to-text translation works today; live spoken translation requires configured STT and TTS providers.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["stt_provider_api_key", "tts_provider_api_key"]),
    _cap(22, "Emotion/urgency detection", "Detect emotional tone or urgency in the user's voice to adapt the response.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an emotion-detection model is configured behind the emotion_detector adapter.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["emotion_detection_model"]),
    _cap(23, "Short driving-mode replies", "Give shorter, glance-free replies suited to a driving/hands-busy context.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a shortened response-formatting profile when driving mode is requested.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(24, "Bluetooth earbuds routing", "Route voice input/output through connected Bluetooth earbuds.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a Bluetooth audio routing worker is configured.",
         CONFIG_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["bluetooth_audio_worker"]),
    _cap(25, "Mobile mic to laptop command routing", "Capture a voice command on a mobile device and route it to a laptop session.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a cross-device mobile worker bridge is configured.",
         CONFIG_CHECK, EPHEMERAL, required_integrations=["mobile_worker_bridge"]),
    _cap(26, "Smartwatch mic trigger", "Trigger voice capture from a paired smartwatch microphone.",
         Risk.LOW, Perm.ALLOWED, Status.PLANNED,
         "No smartwatch worker adapter exists yet; returns a planned/capability_unavailable response.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["smartwatch_worker"]),
    _cap(27, "Smart glasses mic support", "Capture and route voice commands from smart-glasses hardware.",
         Risk.LOW, Perm.ALLOWED, Status.PLANNED,
         "No smart-glasses worker adapter exists yet; returns a planned/capability_unavailable response.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["smart_glasses_worker"]),
    _cap(28, "Meeting transcription with consent", "Transcribe a live meeting's audio, only when all participants' consent is confirmed.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Requires an explicit consent flag before transcription begins; refuses otherwise and returns approval_required.",
         AUDIT_CHECK, APPROVAL_GATED, required_integrations=["stt_provider_api_key"]),
    _cap(29, "Voice note memory with permission", "Save a transcribed voice note into memory, only with explicit user permission.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Requires an explicit permission flag on the request; refuses to store without it.",
         AUDIT_CHECK, APPROVAL_GATED),
    _cap(30, "Voice macro creation", "Define a reusable voice macro (a saved sequence of commands) for later replay.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Stores the macro's command sequence in the DB-backed memory table; does not execute it at creation time.",
         DB_CHECK, DB_SCOPED),
    _cap(31, "Voice-controlled workflows", "Trigger a saved Workflow Agent workflow via a spoken/typed command.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Routes the transcribed/typed command to MasterAgent, which dispatches it to the Workflow Agent.",
         SCHEMA_CHECK, EPHEMERAL),
    _cap(32, "Voice-controlled coding", "Trigger a Code Agent task via a spoken/typed command.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Routes the transcribed/typed command to MasterAgent, which dispatches it to the Code Agent.",
         SCHEMA_CHECK, EPHEMERAL),
    _cap(33, "Voice-controlled CRM", "Trigger a Business Agent CRM action via a spoken/typed command.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Routes the transcribed/typed command to MasterAgent, which dispatches it to the Business Agent.",
         SCHEMA_CHECK, EPHEMERAL),
    _cap(34, "Private mode for sensitive replies", "Suppress or redact spoken/displayed output for sensitive replies.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a redaction formatter to the reply and skips loud TTS playback when private mode is active.",
         AUDIT_CHECK, NOT_PERSISTED),
    _cap(35, "Owner voice recognition before private tasks", "Verify the speaker is the workspace owner before running a private/sensitive task.",
         Risk.HIGH, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Blocks private tasks by default until a speaker-verification model is configured; no task runs on an unverified voice.",
         AUDIT_CHECK, NOT_PERSISTED, required_integrations=["speaker_verification_model"]),
    _cap(36, "Multi-user speaker profiles", "Maintain distinct speaker profiles to distinguish multiple household/team users.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a speaker-verification model is configured; profile metadata storage works today.",
         CONFIG_CHECK, DB_SCOPED, required_integrations=["speaker_verification_model"]),
    _cap(37, "Unknown voice blocking for sensitive actions", "Refuse to run sensitive actions when the speaker's identity cannot be confirmed.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Blocks sensitive actions by default whenever speaker identity cannot be confirmed, since no verification model is configured.",
         AUDIT_CHECK, NOT_PERSISTED),
    _cap(38, "Voice command confirmation for risky actions", "Ask for a spoken/typed confirmation before executing a risky action.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Prompts for an explicit yes/no confirmation before forwarding a risky action to the target agent.",
         AUDIT_CHECK, EPHEMERAL),
    _cap(39, "Voice PIN fallback", "Allow a spoken/typed PIN as a fallback authentication method when voice ID is unavailable.",
         Risk.HIGH, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the entered PIN against a hashed value stored in the DB before allowing a sensitive action to proceed.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(40, "Conversation session timeout", "End an idle voice conversation session automatically after a timeout.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Tracks session inactivity and closes the session state once the configured timeout elapses.",
         SCHEMA_CHECK, EPHEMERAL, audit_required=False),
    _cap(41, "Continuous conversation mode after wake word", "Keep listening for follow-up commands for a short window after the wake word, without repeating it.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a wake-word engine and STT provider are both configured.",
         CONFIG_CHECK, EPHEMERAL, audit_required=False, required_integrations=["wake_word_engine", "stt_provider_api_key"]),
    _cap(42, "Context-aware tone selection", "Choose a reply tone (formal/casual/urgent) based on conversational context.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Selects a tone profile from stored preferences and recent conversation context.",
         DB_CHECK, DB_SCOPED, audit_required=False),
    _cap(43, "Voice persona profile", "Maintain a configurable voice persona (name, tone, style) for the assistant.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Stores/reads the persona profile via the DB-backed memory table.",
         DB_CHECK, DB_SCOPED, audit_required=False),
    _cap(44, "Volume/speed preference memory", "Remember a user's preferred playback volume and speech speed.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Stores/reads volume and speed preferences via the DB-backed memory table.",
         DB_CHECK, DB_SCOPED, audit_required=False),
    _cap(45, "Multi-device audio session manager", "Coordinate a single active voice session across a user's multiple devices.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a multi-device session bridge is configured.",
         CONFIG_CHECK, EPHEMERAL, required_integrations=["multi_device_session_bridge"]),
    _cap(46, "Voice command history by workspace", "List past voice commands scoped to a workspace.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Runs a scoped DB query against the command-history table filtered by workspace_id.",
         DB_CHECK, DB_SCOPED, audit_required=False),
    _cap(47, "Audio privacy redaction metadata", "Tag stored command records with redaction metadata for sensitive audio content.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Attaches a redaction-status field to the persisted record instead of storing raw sensitive audio.",
         DB_CHECK, DB_SCOPED),
    _cap(48, "Voice activation audit logs", "Log every wake-word/voice-activation event for audit purposes.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Writes an audit log row each time voice activation is triggered.",
         AUDIT_CHECK, DB_SCOPED),
    _cap(49, "TTS proof response for completed task", "Speak a short confirmation once a requested task has completed.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns a text confirmation now; spoken confirmation requires a configured TTS provider.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["tts_provider_api_key"]),
    _cap(50, "Voice Agent health/dependency check", "Report Voice Agent health and which STT/TTS/audio adapters are configured.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports process health plus whether STT, TTS, wake-word, and audio-routing adapters are configured.",
         SCHEMA_CHECK, NOT_PERSISTED, audit_required=False),
]

assert len(CAPABILITIES) == 50, f"voice capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
