"""Capability data for the Workflow Agent (agent_key="workflow").

Purpose (from mission spec): Automation pipelines, webhooks, triggers, n8n,
forms, sheets, WhatsApp, CRM, scheduling, monitoring.

Live MVP behavior:
- Generate and validate workflow plans.
- Simulate workflow safely.
- Real n8n/API actions only if configured and approved.
"""

from __future__ import annotations

import re
from typing import List, Optional

from agents.capability_manifest import (
    AgentCapabilityEntry,
    CapabilityPermissionLevel as Perm,
    CapabilityRiskLevel as Risk,
    CapabilityStatus as Status,
)

AGENT_KEY = "workflow"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _cap(
    index: int,
    name: str,
    description: str,
    risk: Risk,
    permission: Perm,
    status: Status,
    safe_mvp_behavior: str,
    verification_method: str,
    memory_policy: str,
    audit_required: bool = True,
    required_integrations: Optional[List[str]] = None,
) -> AgentCapabilityEntry:
    return AgentCapabilityEntry(
        id=f"{AGENT_KEY}.{index:03d}_{_slug(name)}",
        name=name,
        description=description,
        risk_level=risk,
        permission_level=permission,
        status=status,
        required_integrations=required_integrations or [],
        safe_mvp_behavior=safe_mvp_behavior,
        verification_method=verification_method,
        memory_policy=memory_policy,
        audit_required=audit_required,
    )


DB_SCOPED = "Persisted to the DB-backed memory table via the Memory Agent bridge, keyed by user_id + workspace_id."
NOT_PERSISTED = "Not persisted; produces an in-request plan/result without creating a durable record."
APPROVAL_GATED = "Persisted only as part of an approval-request record; live-send/live-write details withheld until resolved."
AUDIT_ONLY = "Not stored as memory; written only to the audit log table for compliance traceability."
EPHEMERAL = "Held only for the lifetime of the active dry-run/simulation; not persisted to durable storage."

SCHEMA_CHECK = "VerificationAgent confirms the generated plan matches the workflow-plan schema."
UNAVAILABLE_CHECK = "N/A while capability_status is external_dependency_required; verification is skipped and surfaced as such."

CAPABILITIES: List[AgentCapabilityEntry] = [
    _cap(1, "Build trigger-action pipelines", "Build a trigger-action automation pipeline definition from a plain description.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a structured, validated pipeline plan (trigger, conditions, actions) as local data; does not execute it.",
         SCHEMA_CHECK, DB_SCOPED, audit_required=False),
    _cap(2, "Workflow plan JSON generation", "Generate a structured JSON representation of a workflow plan.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Serializes the built pipeline plan to validated JSON.",
         SCHEMA_CHECK, DB_SCOPED, audit_required=False),
    _cap(3, "n8n workflow generation", "Generate an n8n-compatible workflow definition from a pipeline plan.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Produces the n8n JSON structure locally; does not deploy it until an n8n instance is configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["n8n_instance_url"]),
    _cap(4, "n8n connector adapter", "Push/pull workflows to/from a live n8n instance.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an n8n instance URL/API key is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["n8n_instance_url", "n8n_api_key"]),
    _cap(5, "Webhook endpoint planning", "Design a webhook endpoint (path, method, payload shape) for a trigger.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Generates a validated webhook contract as local data; does not expose a live endpoint by itself.",
         SCHEMA_CHECK, DB_SCOPED, audit_required=False),
    _cap(6, "Webhook validation", "Validate an incoming/outgoing webhook payload against its expected contract.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Runs a real structural/signature validation against the supplied payload.",
         "Confirmed directly by the validation pass/fail result.", NOT_PERSISTED, audit_required=False),
    _cap(7, "Form-to-Sheet pipeline", "Pipe form submissions into a Google Sheet.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Generates and simulates the pipeline plan; live writes require Google Sheets credentials to be configured.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["google_sheets_api_credentials"]),
    _cap(8, "Form-to-WhatsApp pipeline", "Notify via WhatsApp when a form is submitted.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Generates and simulates the pipeline plan; live sends require WhatsApp Business API credentials.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["whatsapp_business_api_credentials"]),
    _cap(9, "Form-to-CRM pipeline", "Create/update a CRM record when a form is submitted.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Generates and simulates the pipeline plan; live writes require CRM API credentials.",
         UNAVAILABLE_CHECK, DB_SCOPED, audit_required=False, required_integrations=["crm_api_credentials"]),
    _cap(10, "Google Sheets connector adapter", "Read/write rows in a Google Sheet.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until Google Sheets API credentials are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["google_sheets_api_credentials"]),
    _cap(11, "Airtable connector adapter", "Read/write records in an Airtable base.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an Airtable API key is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["airtable_api_key"]),
    _cap(12, "Excel connector adapter", "Read/write rows in an Excel workbook (local file or cloud Excel API).",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until an Excel connector is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["excel_connector"]),
    _cap(13, "CRM connector", "General connector for reading/writing CRM records.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until CRM API credentials are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["crm_api_credentials"]),
    _cap(14, "WhatsApp notification connector", "Send outbound WhatsApp notifications.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until WhatsApp Business API credentials are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["whatsapp_business_api_credentials"]),
    _cap(15, "Email connector", "Send outbound email notifications.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until SMTP credentials are configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["smtp_credentials"]),
    _cap(16, "Slack notification connector", "Send outbound Slack notifications via webhook.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a Slack webhook URL is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["slack_webhook_url"]),
    _cap(17, "Discord notification connector", "Send outbound Discord notifications via webhook.",
         Risk.LOW, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Returns external_dependency_required until a Discord webhook URL is configured.",
         UNAVAILABLE_CHECK, NOT_PERSISTED, audit_required=False, required_integrations=["discord_webhook_url"]),
    _cap(18, "Conditional if/else logic", "Evaluate conditional branches within a workflow plan.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Evaluates real boolean expressions against provided step-output data using local logic.",
         "Confirmed directly by the evaluated branch result.", NOT_PERSISTED, audit_required=False),
    _cap(19, "Lead scoring", "Score an incoming lead based on rule-based criteria.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies a rule-based scoring formula (source, fields completed, engagement) to the lead payload.",
         "VerificationAgent confirms the score matches recomputation from the same inputs.", DB_SCOPED, audit_required=False),
    _cap(20, "Duplicate checking", "Check whether an incoming record is a duplicate of an existing one.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Runs a scoped DB lookup/similarity match against existing records.",
         "Confirmed directly by the DB lookup result.", NOT_PERSISTED, audit_required=False),
    _cap(21, "Spam filtering", "Filter out spam submissions before they enter a pipeline.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies rule-based spam heuristics (honeypot fields, known bad patterns, rate limits).",
         "Confirmed directly by the heuristic match result.", NOT_PERSISTED, audit_required=False),
    _cap(22, "Scheduled workflows", "Run a workflow automatically on a defined schedule (cron-like).",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Registers a scoped schedule entry that the task manager checks and triggers at the configured time.",
         "VerificationAgent confirms a run-log entry was created at the scheduled time.", DB_SCOPED),
    _cap(23, "Delayed actions", "Delay execution of a workflow action by a configured duration.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Schedules the action for future execution via the task manager rather than running it immediately.",
         "VerificationAgent confirms the action executed at/after the configured delay.", DB_SCOPED, audit_required=False),
    _cap(24, "Workflow monitor", "Continuously monitor active workflow runs for failures/stalls.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Polls scoped run-status records and flags runs exceeding expected duration or erroring.",
         "Confirmed directly by the polled run-status data.", NOT_PERSISTED, audit_required=False),
    _cap(25, "Failed-step diagnosis", "Diagnose why a specific workflow step failed.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Inspects the step's captured error/output and matches it against known-cause heuristics.",
         "Confirmed directly by the inspected step error data.", DB_SCOPED, audit_required=False),
    _cap(26, "Safe retries", "Automatically retry a failed workflow step when classified as safe/idempotent.",
         Risk.MEDIUM, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Retries only steps tagged non-sensitive, up to a configured retry limit, logging every attempt.",
         "Confirmed by re-checking the step's own postcondition after retry.", DB_SCOPED),
    _cap(27, "No duplicate lead retry", "Prevent a retried step from creating a duplicate lead/record.",
         Risk.MEDIUM, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Rechecks for an existing matching record before any retry-created write and skips the write if one already exists.",
         "Confirmed directly by the duplicate-check result before the retry write.", NOT_PERSISTED),
    _cap(28, "Approval gates", "Pause a workflow at a designated step until explicit approval is granted.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.AVAILABLE,
         "Halts execution at the gate step and creates a Security Agent approval request; resumes only on approval.",
         "Confirmed directly by the approval-request record's resolved state.", APPROVAL_GATED),
    _cap(29, "Workflow templates", "Provide reusable pre-built workflow templates for common use cases.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Returns a library of locally stored, validated template plans.",
         "VerificationAgent confirms the returned template matches the stored template schema.", DB_SCOPED, audit_required=False),
    _cap(30, "Plain-language workflow builder", "Translate a plain-language description into a structured workflow plan.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Parses the description into a structured plan using rule-based/keyword mapping; does not execute it.",
         SCHEMA_CHECK, DB_SCOPED, audit_required=False),
    _cap(31, "n8n JSON exporter", "Export a workflow plan as n8n-compatible JSON without requiring a live n8n connection.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Serializes the local pipeline plan into n8n's JSON node/connection format.",
         "VerificationAgent confirms the exported JSON parses as valid n8n workflow format.", NOT_PERSISTED, audit_required=False),
    _cap(32, "API connector generation", "Generate a connector definition for a generic REST API integration.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Produces a structured connector definition (endpoint, auth type, mapping) from provided API details; does not call the API until credentials are supplied.",
         "VerificationAgent confirms the connector definition matches the expected schema.", DB_SCOPED, audit_required=False),
    _cap(33, "Workflow health dashboard", "Provide aggregate health metrics (success rate, failures) for workflows.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Computes counts/aggregates from scoped run-log records.",
         "Confirmed directly by the underlying aggregate query.", NOT_PERSISTED, audit_required=False),
    _cap(34, "Hot lead alerts", "Send an alert when a lead is scored above a hot-lead threshold.",
         Risk.MEDIUM, Perm.ALLOWED, Status.EXTERNAL_DEPENDENCY_REQUIRED,
         "Detects the threshold crossing locally; live notification delivery requires a configured notification connector.",
         UNAVAILABLE_CHECK, DB_SCOPED, required_integrations=["slack_webhook_url", "whatsapp_business_api_credentials"]),
    _cap(35, "Client onboarding automation", "Automate the sequence of steps for onboarding a new client.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Generates and can dry-run the onboarding pipeline plan; live external steps require their respective connectors.",
         "VerificationAgent confirms each onboarding step's postcondition.", DB_SCOPED),
    _cap(36, "Support ticket routing", "Route an incoming support ticket to the correct team/queue based on rules.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Applies rule-based routing criteria (keywords, priority, category) to the ticket payload.",
         "Confirmed directly by the routing-rule match result.", DB_SCOPED, audit_required=False),
    _cap(37, "Payment reminder workflows with approval", "Send payment reminders to clients, gated behind explicit approval before any real send.",
         Risk.HIGH, Perm.APPROVAL_REQUIRED, Status.APPROVAL_REQUIRED,
         "Generates the reminder plan and blocks the live send step until Security Agent approval is recorded.",
         "Confirmed directly by the approval-request record's resolved state.", APPROVAL_GATED),
    _cap(38, "Workflow memory", "Persist workflow definitions and run history to memory for recall.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes workflow plans/run summaries to the DB-backed memory table via the Memory Agent bridge.",
         "Confirmed by re-reading back the saved row.", DB_SCOPED, audit_required=False),
    _cap(39, "Connected tools registry", "Track which external connectors (Sheets, CRM, Slack, etc.) are configured for a workspace.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reads configured-integration flags and reports them without exposing raw credentials.",
         "Confirmed directly by the configuration-flag read.", DB_SCOPED, audit_required=False),
    _cap(40, "Workflow run logs", "Record a structured log of every workflow run and its per-step outcomes.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes a scoped run-log record to the DB for every execution/dry-run.",
         "Confirmed by re-reading back the written run-log row.", DB_SCOPED),
    _cap(41, "Workflow event WebSocket", "Stream real-time workflow run events to the dashboard.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Publishes scoped workflow run events onto the existing WebSocket channel as they occur.",
         "Confirmed directly by the published event matching the run-log record.", EPHEMERAL, audit_required=False),
    _cap(42, "Workflow dry-run mode", "Execute a workflow plan in dry-run mode without performing any live external action.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Runs each step's logic against simulated/sample data and reports what would have happened.",
         "VerificationAgent confirms no live connector call was made during the dry run.", EPHEMERAL, audit_required=False),
    _cap(43, "Workflow simulation mode", "Simulate a full workflow run end-to-end using representative test data.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Runs the plan against supplied test data through the same step logic, without touching live external systems.",
         "VerificationAgent confirms all steps report simulated, not live, execution.", EPHEMERAL, audit_required=False),
    _cap(44, "Workflow rollback plan", "Generate a rollback plan describing how to undo a workflow's effects.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Derives a rollback plan from each step's declared inverse action; does not execute the rollback automatically.",
         "VerificationAgent confirms the rollback plan covers every step with a recorded state change.", DB_SCOPED, audit_required=False),
    _cap(45, "Workflow permission policy", "Enforce which users/roles may create, run, or approve workflows.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Checks the caller's role/permission against the Security Agent's per-agent policy before allowing the action.",
         "Confirmed directly by the Security Agent policy check result.", AUDIT_ONLY),
    _cap(46, "Workflow secret reference checker", "Prevent workflow plans from embedding raw secrets/credentials instead of secret references.",
         Risk.HIGH, Perm.BLOCKED_BY_DEFAULT, Status.AVAILABLE,
         "Scans generated workflow JSON for literal secret-shaped values and rejects the plan if found, requiring a secrets_manager reference instead.",
         "Confirmed directly by the scan result on the generated plan.", AUDIT_ONLY),
    _cap(47, "Workflow report builder", "Build a structured report summarizing a workflow's runs, outcomes, and metrics.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Compiles scoped run-log and metric data into a structured report.",
         "Confirmed directly by the underlying report query.", NOT_PERSISTED, audit_required=False),
    _cap(48, "Workflow Agent health/dependency check", "Report Workflow Agent health and which optional connectors (n8n, Sheets, Slack, etc.) are configured.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Reports DB connectivity and which named integrations are configured versus missing.",
         "Self-verified: reports its own configuration state directly.", NOT_PERSISTED, audit_required=False),
    _cap(49, "Workflow audit log", "Record every workflow creation/run/approval action to the audit log.",
         Risk.LOW, Perm.ALLOWED, Status.AVAILABLE,
         "Writes a scoped audit record for every workflow lifecycle event to the DB-backed audit log table.",
         "Confirmed by re-reading back the written audit row.", AUDIT_ONLY),
    _cap(50, "Workflow-to-Business handoff", "Hand off workflow outcomes/data to the Business Agent for downstream analysis.",
         Risk.MEDIUM, Perm.ALLOWED, Status.AVAILABLE,
         "Forwards the structured workflow result to the Business Agent's task queue.",
         "Confirmed by the Business Agent's task-received acknowledgment.", DB_SCOPED),
]

assert len(CAPABILITIES) == 50, f"workflow capability_data must declare exactly 50 entries, got {len(CAPABILITIES)}"
