"""add files table

Revision ID: af60ed6c1906
Revises: dca2ceaecdcc
Create Date: 2026-07-11 00:26:54.831239+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af60ed6c1906'
down_revision: Union[str, None] = 'dca2ceaecdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.String(length=140), nullable=False),
    sa.Column('workspace_id', sa.String(length=140), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=140), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_files_workspace_category', ['workspace_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_files_workspace_user', ['workspace_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_workspace_user')
        batch_op.drop_index(batch_op.f('ix_files_workspace_id'))
        batch_op.drop_index('ix_files_workspace_category')
        batch_op.drop_index(batch_op.f('ix_files_user_id'))

    op.drop_table('files')
    # ### end Alembic commands ###
